---
version: 0
os: Linux

files:
  - source: /
    destination: /srv/EDGYFIWEB
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: change_permissions.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: change_permissions.sh
      timeout: 300
