---
version: 0
os: Linux

files:
  - source: /
    destination: /srv/EDGYFIWEB
file_exists_behavior: OVERWRITE
permissions:
  - object: /srv/EDGYFIWEB
    pattern: "**"
    except: null
    owner: ec2-user
    mode: 777
hooks:
  BeforeInstall:
    - location: change_permissions.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: change_permissions.sh
      timeout: 300
