---
version: 0
os: linux

---
files:
  - source: /
    destination: /srv/EDGYFIWEB
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: change_permissions.sh
      timeout: 300
      runas: root
